---
title: "Ecological Modeling"
output: html_document
---

```{css, echo=FALSE}
#header {
  background: url(https://linesteppers.com/tutorials/RMarkdown/img/BannerImage_TreeBlossoms_4470x3024.jpg);
  padding: .5em;
}
```

<!-- ## Syllabus -->

**Instructor:** Caleb Roberts

<!-- ## Tentative Schedule -->

<!-- | Week | Day | Date     |   Topic                                                                        | Notes      | ...        | -->
<!-- |------|-----|----------|--------------------------------------------------------------------------------|------------|------------| -->
<!-- | 1    | Tue | Aug. 18  |   What is “modeling?” and WHY model?                                           |------------|------------| -->
<!-- |      | Thu | Aug. 20  |   Coding crash course: loops, functions, tidyverse                             |------------|------------| -->
<!-- | 2    | Tue | Aug. 27  |   Data exploration                                                             |------------|------------| -->
<!-- |      | Thu | Aug. 29  |   Data exploration                                                             |------------|------------| -->
<!-- | 3    | Tue | Sep. 3   |   Review of linear models, probability distributions                           |------------|------------| -->
<!-- |      | Thu | Sep. 5   |   Review of linear models, probability distributions                           |------------|------------| -->
<!-- | 4    | Tue | Sep. 10  |   No class                                                                     |------------|------------| -->
<!-- |      | Thu | Sep. 12  |   No class                                                                     |------------|------------| -->
<!-- | 5    | Tue | Sep. 17  |   Model selection                                                              |------------|------------| -->
<!-- |      | Thu | Sep. 19  |   Model selection                                                              |------------|------------| -->
<!-- | 6    | Tue | Sep. 24  |   Autocorrelation                                                              |------------|------------| -->
<!-- |      | Thu | Sep. 26  |   Mixed models: what, why, how?                                                |------------|------------| -->
<!-- | 7    | Tue | Oct. 1   |   Mixed models: LMM lab                                                        |------------|------------| -->
<!-- |      | Thu | Oct. 3   |   Mixed models: GLMM                                                           |------------|------------| -->
<!-- | 8    | Tue | Oct. 8   |   Mixed models: GLMM lab                                                       |------------|------------| -->
<!-- |      | Thu | Oct. 10  |   Generalized additive models                                                  |------------|------------| -->
<!-- | 9    | Tue | Oct. 15  |   No class: Fall Break                                                         |------------|------------| -->
<!-- |      | Thu | Oct. 17  |   Generalized additive models                                                  |------------|------------| -->
<!-- | 10   | Tue | Oct. 22  |   No class                                                                     |------------|------------| -->
<!-- |      | Thu | Oct. 24  |   Hierarchical generalized additive models                                     |------------|------------| -->
<!-- | 11   | Tue | Oct. 29  |   Hierarchical generalized additive models                                     |------------|------------| -->
<!-- |      | Thu | Oct. 31  |   Guest lecture: Brandon Edwards                                               |------------|------------| -->
<!-- | 12   | Tue | Nov. 5   |   Hello, Bayes!                                                                |------------|------------| -->
<!-- |      | Thu | Nov. 7   |   Bayesian models: Linear models lab                                           |------------|------------| -->
<!-- | 13   | Tue | Nov. 12  |   Bayesian models: Stan language lab                                           |------------|------------| -->
<!-- |      | Thu | Nov. 14  |   Bayesian models: Mixed models lab                                            |------------|------------| -->
<!-- | 14   | Tue | Nov. 19  |   Loose ends day                                                               |------------|------------| -->
<!-- |      | Thu | Nov. 21  |   Writing methods and results                                                  |------------|------------| -->
<!-- | 15   | Tue | Nov. 26  |   Writing methods and results                                                  |------------|------------| -->
<!-- |      | Thu | Nov. 28  |   No class: Thanksgiving                                                       |------------|------------| -->


# Welcome!

This is the course website for Ecological Modeling. Navigate through the tabs above to find the lab exercises and homeworks for the course.

# Course Goals

Students will be able to:

  * Identify and summarize statistical results as presented in peer reviewed articles  
  * Use R to conduct model-based analyses of ecological data 
  * Combine statistical results and ecological knowledge to support a conclusion 
  * Evaluate the presentation of statistical results as written

# Texts

*(all texts are freely-available in electronic format)* - 

  * Zuur et al. 2009: Mixed effects models and extensions in ecology with R
  * Hobbs and Hooten 2015: Bayesian Models: A Statistical Primer for Ecologists 
  * Additional outside readings will be assigned in class and made available via Blackboard. 

<!-- **Class Format:** -->

<!-- During the first few weeks, each student will briefly introduce their research question and data and we will go over basics of how to use R and interact with the course content on this website using R markdown files and GitHub. From then on, one selected topic will be covered during each class. First the instructor will briefly summarize the assigned reading (~15 min) and go over key concepts and analyses, R packages and how they should be used, how to differentiate among them, including time for questions and clarification. Then, a student will present an example of the topic (~15 min). This could be (1) going over an example presented in the text by walking through the procedure and details of the code that they think are important; or (2) applying these techniques to the student's own data and walking others through the analysis, and present on their results/challenges faced, etc. Each class concludes with a ~20-min discussion led by the student (who will come prepared with questions to facilitate discussion and will share novel/important/interesting functions and pieces of R code). Each student will lead 1 or 2 topics during the quarter. We will also have a mid-term and final presentation and discussion on student projects. Students will prepare their lesson content ahead of time by modifying the Rmarkdown webpage on this site. -->

<!-- **Final product:** -->

<!-- Each student will complete the results section to include in a paper to submit for publication or data collection plans for a research proposal. -->



<!-- ## Before Class  -->

<!-- Before the first class please read through the [computer setup instructions](00-computer-setup.html) that walk you through how to set up your computer to run R and Rstudio. Even if you have these programs already installed, make sure to check that you are running the latest versions of R and RStudio (which the instructions will tell you how to do).  -->

<!-- Our course website runs from a repository on GitHub. You can view this repository [here](https://github.com/fukamilab/BIO202). Notice that the repository has 2 files for each lesson webpage (named 00-lesson-topic), one is an html file (.html) that is displayed as a webpage while the other is a R markdown (.Rmd) file that will allow us to write R code and explanatory text in the same file. The html file is created by R Studio from the R markdown file. The repository also has a folder called "data". This is where we will put data files used by our example code. Note that this repository can be downloaded by anyone on the internet. If you have data that you wish to use in class but do not wish to share with the entire WWW, you are welcome to email the data files to the rest of the class prior to your lesson. -->

<!-- During class you will be editing the course webpages to include R code for the lesson discussion that you lead. If you are familiar with git and have a GitHub account, you should fork the repository to your account so that you can make changes there. If that is gibberish to you- don't worry! You can either choose to edit the course webpages by downloading them and emailing any edits to Jes (see [computer setup instructions](00-computer-setup.html)) or you can choose to learn a little git and create you own GitHub account during an optional class session during the first week.  -->

<!-- ## References & Readings -->

<!-- ### Assigned Readings -->

<!-- All assigned readings can be obtained for free through Stanford library online resources.  -->

<!-- + Bivand, R. S., Pebesma, E., Gomez-Rubio, V. (2013), *Applied Spatial Data Analysis with R*, 2nd ed. Springer. [Stanford Full Text](https://link-springer-com.stanford.idm.oclc.org/book/10.1007%2F978-1-4614-7618-4) -->
<!-- + Borcard, D., Gillet, F. and Legendre, P. (2011), *Numerical Ecology with R.* Springer. [Stanford Full Text](https://link.springer.com/book/10.1007/978-1-4419-7976-6) -->
<!-- + Korner-Nievergelt et al. (2015), *Bayesian data analysis in ecology using linear models with R, BUGS, and Stan.* Elsevier. [Stanford Full Text](http://www.sciencedirect.com/science/book/9780128013700) -->
<!-- + Legendre, P. and Legendre, L. (2012), *Numerical Ecology*. Elsevier. [Stanford Full Text](http://www.sciencedirect.com/science/bookseries/01678892/24) -->
<!-- + Martin, T. G., Wintle, B. A., Rhodes, J. R., Kuhnert, P. M., Field, S. A., Low-Choy, S. J., Tyre, A. J. and Possingham, H. P. (2005), Zero tolerance ecology: improving ecological inference by modelling the source of zero observations. *Ecology Letters*, 8: 1235-1246. DOI:[10.1111/j.1461-0248.2005.00826.x](http://dx.doi.org/10.1111/j.1461-0248.2005.00826.x) -->
<!-- + Ramette, A. (2007), Multivariate analyses in microbial ecology. *FEMS Microbiology Ecology*, 62: 142-160. DOI: [10.1111/j.1574-6941.2007.00375.x](http:dx.doi.org/10.1111/j.1574-6941.2007.00375.x) -->
<!-- + Wickham, H. (2016), *ggplot2: Elegant Graphics for Data Analysis*. Springer. [Stanford Full Text](https://link-springer-com.stanford.idm.oclc.org/book/10.1007%2F978-3-319-24277-4) -->
<!-- + Zuur, A. F., Leno, E. N., Walker, N., Savliev, A. A. and Smith, G. M. (2009), *Mixed Effect Models and Extensions in Ecology with R.* Springer. [Stanford Full Text](https://link.springer.com/book/10.1007%2F978-0-387-87458-6) -->
<!-- + Zuur, A. F. (2010), A protocol for data exploration to avoid common statistical problems. *Methods in Ecology and Evolution*, 1: 3-14. DOI: [10.1111/j.2041-210X.2009.00001.x](http://dx.doi.org/10.1111/j.2041-210X.2009.00001.x) -->

<!-- ### Additional Suggested References -->

<!-- + Beale, C. M., Lennon, J. J., Yearsley, J. M., Brewer, M. J. and Elston, D. A. (2010), Regression analysis of spatial data. *Ecology Letters*, 13: 246-264. DOI:[10.1111/j.1461-0248.2009.01422.x](http://dx.doi.org/10.1111/j.1461-0248.2009.01422.x) -->
<!-- +Hawkins, B. A. (2012), Eight (and a half) deadly sins of spatial analysis. *Journal of Biogeography*, 39: 1-9. [DOI: 10.1111/j.1365-2699.2011.02637.x](http://dx.doi.org/10.1111/j.1365-2699.2011.02637.x) -->
<!-- + McElreath, R. (2016), *Statistical rethinking: a Bayesian course with examples in R and Stan*. CRC Press. *Available in the Science and Marine libraries* [Author's website](http://xcelab.net/rm/statistical-rethinking/) -->
<!-- + Venables, W. N., Smith, D. M. and the R Core Team. (2012), *An Introduction to R: Notes on R: A Programming Environment for Data Analysis and Graphics*. Version 2.15.1. [full text](https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf) -->
<!-- + Wagner, H. H. and Fortin, M. J. (2005), Spatial analysis of landscapes: concepts and statistics. *Ecology*, 86: 1975–1987. DOI: [10.1890/04-0914](http://dx.doi.org/10.1890/04-0914) -->
<!-- + Zuur, A. F., Hilbe, J. M. and Ieno, E. N. (2013), *A beginner's guide to GLM and GLMM with R: a frequentist and Bayesian perspective for ecologists.* Highland Statistics Ltd. [Stanford Library Record](https://searchworks.stanford.edu/view/11749213)  -->
